### ISSUE TITLE
simplest IPC , feature request

### ISSUE THREAD

**Issue by Pogakl** [z505/SimpleIPC-lib#1]
```
(* instead client/server i propose p2p like nodes within a single computer *)
(* dont worry about node discovery and such , that is my fun ToDo *)
(* and reject my humble request if your time worths a lot right now *)

library SimplestIPC;(*i can strip down but you know better*)

const X:integer=1024; (*optimal size unknown in advance*) 
type  message=array[1..X] of byte;
      nodeID = (*you know better*)      

function  StartServer(ServerName:string):nodeID;
procedure SendMsg(DestNode:nodeID, s:message);
```
Did i miss something ? I made account in GitHub today just because of your gemstone.
Your concept is great , but i think i can show you magic if you dare to provide me the simplest version.
Thanks in advance and i hope we can work together , i have plenty of time to offer.

**Comment by z505** [comment]
Will you work on it with a Fork if you want?
At this moment I have no time to work on this project but will return to it later for many tools with Go delphi and fpc

**Comment by Pogakl** [comment]
Thank you for your fast and clean response.
I will watch your page , as i said it is not urgent and my experience working at GitHub is zero.
I can emulate the functionality of simplestIPC or use alternatives for now so all good.
I think is better for all of us to publish here in Github the concept of my project later to supply orientation for worthy coders like you - EC
